export const SET_FILES = 'SET_FILES'
export const SET_LOADING_FILES = 'SET_LOADING_FILES'
export const GET_FILES_ERROR = 'GET_FILES_ERROR'

export const SET_LOADING_CONTENTS = 'SET_LOADING_CONTENTS'
export const GET_CONTENTS_SUCCESS = 'GET_CONTENTS_SUCCESS'
export const GET_CONTENTS_ERROR = 'GET_CONTENTS_ERROR'


export const SET_MODAL_OPEN = 'SET_MODAL_OPEN'
export const SET_ALERT_SHOWN = 'SET_ALERT_SHOWN'

